"""add_balance_to_user

Revision ID: 22890229649c
Revises: e674cb879857
Create Date: 2024-11-06 21:52:58.899911

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22890229649c"
down_revision: Union[str, None] = "e674cb879857"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_accounts", sa.Column("balance", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_accounts", "balance")
    # ### end Alembic commands ###
