"""many-to-many

Revision ID: 2da352f7334c
Revises: 8e5377f93581
Create Date: 2024-11-05 22:53:07.107746

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "2da352f7334c"
down_revision: Union[str, None] = "8e5377f93581"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("email", table_name="user_accounts")
    op.drop_index("uid", table_name="user_accounts")
    op.drop_index("username", table_name="user_accounts")
    op.drop_table("user_accounts")
    op.drop_table("characters")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characters",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("short_name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("description", mysql.TEXT(), nullable=True),
        sa.Column("background_image", mysql.TEXT(), nullable=True),
        sa.Column("profile_image", mysql.TEXT(), nullable=True),
        sa.Column("original_price", mysql.FLOAT(), nullable=True),
        sa.Column("new_price", mysql.FLOAT(), nullable=True),
        sa.Column("percentage_discount", mysql.FLOAT(), nullable=True),
        sa.Column(
            "created_at",
            mysql.TIMESTAMP(),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.TIMESTAMP(),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "user_accounts",
        sa.Column("uid", mysql.VARCHAR(length=36), nullable=False),
        sa.Column("username", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("first_name", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("last_name", mysql.VARCHAR(length=255), nullable=True),
        sa.Column(
            "is_verified",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("email", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("password_hash", mysql.VARCHAR(length=255), nullable=False),
        sa.Column(
            "created_at",
            mysql.TIMESTAMP(),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.Column("role", mysql.VARCHAR(length=50), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("username", "user_accounts", ["username"], unique=True)
    op.create_index("uid", "user_accounts", ["uid"], unique=True)
    op.create_index("email", "user_accounts", ["email"], unique=True)
    # ### end Alembic commands ###
